# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription(18da4f51-8db5-479b-ba54-e2e4bfba78f0)'
    subscriptionId: '18da4f51-8db5-479b-ba54-e2e4bfba78f0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'kh-appservice'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'infra/main.bicep'
    overrideParameters: 'name=as-python01'
    deploymentMode: 'Incremental'
    
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: '94224483-1132-4a10-82d7-ff981727ca21'
    pipeline: '1'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'




